[font]
size = 16

[font.normal]
#family = "UbuntuMono Nerd Font"
family = "JetBrains Mono"

[window]
#decorations = "none"

[env]
TERM = "xterm-256color"

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 7
y = 0

[general]

# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
#[colors.primary]
#background = '#0d1b1e' # Deep, dark teal
#foreground = '#e0f2f1' # Very light, crisp seafoam white
#
#[colors.cursor]
#text = '#0d1b1e'
#cursor = '#14b8a6' # Vibrant teal accent
#
#[colors.selection]
#text = '#0d1b1e'
#background = '#2dd4bf' # Bright teal highlight
#
#[colors.normal]
#black = '#11292c'
#red = '#f43f5e'
#green = '#0d9488' # Pine/Teal green
#yellow = '#eab308'
#blue = '#06b6d4' # Cyan-blue
#magenta = '#b2dfdb'
#cyan = '#14b8a6' # Primary Teal
#white = '#ccebe8'
#
#[colors.bright]
#black = '#1e464b'
#red = '#fda4af'
#green = '#2dd4bf' # Bright Teal
#yellow = '#fef08a'
#blue = '#67e8f9'
#magenta = '#e0f2f1'
#cyan = '#2dd4bf' # Bright Teal
#white = '#f0fdfa'


[terminal]

[terminal.shell]
program = "tmux"
