#!/bin/bash

set -euo pipefail

if ! command -v chezmoi >/dev/null; then
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply https://github.com/pcrepeau/dotfiles.git
fi

curl -sS https://starship.rs/install.sh | sh

exit 0
