"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "$directory$os$git_branch$git_status$nodejs$rust$golang$php $character"

[os]
disabled = false
format = "[$symbol](#blue) "

[os.symbols]
AIX = "➿ "
Alpaquita = "🔔 "
AlmaLinux = " "        # nf-linux-almalinux
Alpine = " "           # nf-linux-alpine
Amazon = "🙂 "
Android = " "          # nf-fa-android
Arch = " "             # nf-linux-archlinux
Artix = " "            # nf-linux-artix
Bluefin = "🐟 "
CachyOS = "🎗️ "
CentOS = " "           # nf-linux-centos
Debian = " "           # nf-linux-debian
DragonFly = "🐉 "
Emscripten = "🔗 "
EndeavourOS = " "      # nf-linux-endeavour
Fedora = " "           # nf-linux-fedora
FreeBSD = " "          # nf-linux-freebsd
Garuda = " "           # nf-linux-garuda
Gentoo = " "           # nf-linux-gentoo
HardenedBSD = "🛡️ "
Illumos = " "          # nf-linux-illumos
Kali = " "             # nf-linux-kali_linux
Linux = " "            # nf-linux-tux
Mabox = "📦 "
Macos = " "            # nf-linux-apple
Manjaro = " "          # nf-linux-manjaro
Mariner = "🌊 "
MidnightBSD = "🌘 "
Mint = " "             # nf-linux-linuxmint
NetBSD = "🚩 "
NixOS = " "            # nf-linux-nixos
Nobara = " "           # nf-linux-nobara
OpenBSD = " "          # nf-linux-openbsd
OpenCloudOS = "☁️ "
openEuler = "🦉 "
openSUSE = " "         # nf-linux-opensuse
OracleLinux = " "      # nf-dev-oracle
Pop = " "              # nf-linux-pop_os
Raspbian = " "         # nf-linux-raspberry_pi
Redhat = " "           # nf-linux-redhat
RedHatEnterprise = " " # nf-linux-redhat
RockyLinux = " "       # nf-linux-rocky_linux
Redox = "🧪 "
Solus = " "            # nf-linux-solus
SUSE = " "             # nf-fa-suse
Ubuntu = " "           # nf-linux-ubuntu
Ultramarine = "🔷 "
Unknown = "❓ "
Uos = "🐲 "
Void = " "             # nf-linux-void
Windows = " "          # nf-custom-windows


[directory]
format            = "[$path](cyan) "
truncation_length = 4
truncate_to_repo  = true

[git_branch]
symbol = ""
format = "[$symbol $branch](bold purple) "

[git_status]
format     = "($ahead_behind$staged$modified$untracked$deleted$conflicted)"
ahead      = "[⇡$count ](bold cyan)"
behind     = "[⇣$count ](bold cyan)"
diverged   = "[⇡$ahead_count⇣$behind_count ](bold cyan)"
staged     = "[+$count ](bold green)"
modified   = "[●$count ](bold yellow)"
untracked  = "[?$count ](bold white)"
deleted    = "[✘$count ](bold red)"
conflicted = "[⚡$count ](bold red)"

[nodejs]
symbol = ""
format = "[$symbol $version](green) "

[rust]
symbol = ""
format = "[$symbol $version](red) "

[golang]
symbol = ""
format = "[$symbol $version](cyan) "

[php]
symbol = ""
format = "[$symbol $version](purple) "

[character]
success_symbol = "[❯](green)"
error_symbol   = "[❯](red)"
vimcmd_symbol  = "[❮](blue)"
