[tools]
bat = "latest"
chezmoi = "latest"
neovim = "latest"
ripgrep = "latest"
lsd = "latest"
fzf = "latest"
fd = "latest"
node = "latest"
usage = "latest"  # for mise completion
lazygit = "latest"


# "ubi:fluxcd/flux2" = { version = "latest", exe = "flux" }
